backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - label: "Sections"
    name: "sections"
    files:
      - label: "Landing"
        name: "landing"
        file: "src/pages/landing/index.md"
        fields:
         - {label: "Landing Heading", name: "landingHeading", widget: "string"}
         - {label: "Subtitle", name: "subtitle", widget: "string"}
         - {label: "Background Image", name: "backgroundImage", widget: "image"}